const actions = {
     ADD_USER : 'ADD_USER',
     REMOVE_USER : 'REMOVE_USER',
     UPDATE_USER_INFO:'UPDATE_USER_INFO',
     ADD_TO_RECEPIENTS_ARRAY:'ADD_TO_RECEPIENTS_ARRAY',
     REMOVE_FROM_RECEPIENTS_ARRAY:'REMOVE_FROM_RECEPIENTS_ARRAY',
     ADD_RECEPIENT : 'ADD_RECEPIENT',
     REMOVE_ONERECEPIENT : 'REMOVE_ONERECEPIENT',
     REMOVE_ALLRECEPIENTS : 'REMOVE_ALLRECEPIENTS',
     UPDATE_RECEPIENT_INFO : 'UPDATE_RECEPIENT_INFO',

};

export default actions;